using System;
using System.Threading.Tasks;
using Oracle.ManagedDataAccess.Client;

namespace ZKTecoRealTimeLog.Database
{
    /// <summary>
    /// Oracle database provider
    /// </summary>
    public class OracleProvider : IDatabaseProvider
    {
        private readonly string _connectionString;
        private readonly bool _enabled;

        public string ProviderName => "Oracle";
        public bool IsEnabled => _enabled;

        public OracleProvider(DatabaseConfig config)
        {
            _enabled = config.Enabled;

            if (!string.IsNullOrEmpty(config.ConnectionString))
            {
                _connectionString = config.ConnectionString;
            }
            else
            {
                // Default port for Oracle is 1521
                var port = string.IsNullOrEmpty(config.Port) ? "1521" : config.Port;
                _connectionString = $"Data Source={config.Host}:{port}/{config.Database};User Id={config.User};Password={config.Password};";
            }
        }

        public async Task<bool> TestConnectionAsync()
        {
            if (!IsEnabled) return false;

            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Connection test failed: {ex.Message}");
                return false;
            }
        }

        public async Task InitializeDatabaseAsync()
        {
            if (!IsEnabled) return;

            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();

                // Check if table exists
                var checkTableSql = "SELECT COUNT(*) FROM user_tables WHERE table_name = 'ATTENDANCE_LOGS'";
                await using var checkCmd = new OracleCommand(checkTableSql, conn);
                var tableExists = Convert.ToInt32(await checkCmd.ExecuteScalarAsync()) > 0;

                if (!tableExists)
                {
                    var createTableSql = @"
                        CREATE TABLE attendance_logs (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id VARCHAR2(50) NOT NULL,
                            event_time TIMESTAMP NOT NULL,
                            is_valid NUMBER(1) NOT NULL,
                            att_state NUMBER NOT NULL,
                            att_state_desc VARCHAR2(50),
                            verify_method NUMBER NOT NULL,
                            verify_method_desc VARCHAR2(50),
                            work_code NUMBER DEFAULT 0,
                            device_ip VARCHAR2(50),
                            device_name VARCHAR2(100),
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                        )
                    ";
                    await using var createCmd = new OracleCommand(createTableSql, conn);
                    await createCmd.ExecuteNonQueryAsync();

                    var createIndex1 = "CREATE INDEX idx_att_logs_user_id ON attendance_logs(user_id)";
                    await using var idx1Cmd = new OracleCommand(createIndex1, conn);
                    await idx1Cmd.ExecuteNonQueryAsync();

                    var createIndex2 = "CREATE INDEX idx_att_logs_event_time ON attendance_logs(event_time)";
                    await using var idx2Cmd = new OracleCommand(createIndex2, conn);
                    await idx2Cmd.ExecuteNonQueryAsync();
                }

                Console.WriteLine("[Oracle] Database initialized successfully");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error initializing database: {ex.Message}");
            }
        }

        public async Task InsertAttendanceLogAsync(
            string enrollNumber, DateTime eventTime, bool isValid, int attState, string attStateDesc,
            int verifyMethod, string verifyMethodDesc, int workCode, string? deviceIp = null, string? deviceName = null)
        {
            if (!IsEnabled) return;

            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();

                var insertSql = @"
                    INSERT INTO attendance_logs 
                    (user_id, event_time, is_valid, att_state, att_state_desc, verify_method, verify_method_desc, work_code, device_ip, device_name)
                    VALUES 
                    (:userId, :eventTime, :isValid, :attState, :attStateDesc, :verifyMethod, :verifyMethodDesc, :workCode, :deviceIp, :deviceName)
                ";

                await using var cmd = new OracleCommand(insertSql, conn);
                cmd.Parameters.Add(":userId", enrollNumber);
                cmd.Parameters.Add(":eventTime", eventTime);
                cmd.Parameters.Add(":isValid", isValid ? 1 : 0);
                cmd.Parameters.Add(":attState", attState);
                cmd.Parameters.Add(":attStateDesc", attStateDesc);
                cmd.Parameters.Add(":verifyMethod", verifyMethod);
                cmd.Parameters.Add(":verifyMethodDesc", verifyMethodDesc);
                cmd.Parameters.Add(":workCode", workCode);
                cmd.Parameters.Add(":deviceIp", (object?)deviceIp ?? DBNull.Value);
                cmd.Parameters.Add(":deviceName", (object?)deviceName ?? DBNull.Value);

                await cmd.ExecuteNonQueryAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error inserting attendance log: {ex.Message}");
            }
        }

        public async Task InitializeAttendanceTablesAsync()
        {
            if (!IsEnabled) return;
            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();

                // Check Employee Table
                var checkEmp = new OracleCommand("SELECT COUNT(*) FROM user_tables WHERE table_name = 'EMPLOYEE'", conn);
                if (Convert.ToInt32(await checkEmp.ExecuteScalarAsync()) == 0)
                {
                    var sql = @"
                        CREATE TABLE Employee (
                            empId VARCHAR2(255) NOT NULL PRIMARY KEY,
                            empnickName VARCHAR2(255) DEFAULT '',
                            empGivenName VARCHAR2(255) DEFAULT '',
                            empFamilyName VARCHAR2(255) DEFAULT '',
                            gender NUMBER DEFAULT 0,
                            address VARCHAR2(255) DEFAULT '',
                            img VARCHAR2(255),
                            img_jshfilename VARCHAR2(255),
                            empTel VARCHAR2(255) DEFAULT '',
                            empEmail VARCHAR2(255) DEFAULT '',
                            dateOfBirth DATE DEFAULT SYSDATE,
                            age NUMBER,
                            depId VARCHAR2(255),
                            positionId VARCHAR2(255),
                            empStatus NUMBER DEFAULT 1,
                            joinDate DATE DEFAULT SYSDATE,
                            StartCutIns DATE,
                            AcceptDate DATE,
                            empRetireDate DATE,
                            empRemark CLOB,
                            hourlyRate NUMBER DEFAULT 0,
                            seatID NUMBER DEFAULT 0,
                            seatNumber NUMBER,
                            empHobby CLOB,
                            createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            createdBy VARCHAR2(255),
                            updateby VARCHAR2(255)
                        )
                    ";
                    await new OracleCommand(sql, conn).ExecuteNonQueryAsync();
                }

                // Check WorkRecord Table
                var checkWr = new OracleCommand("SELECT COUNT(*) FROM user_tables WHERE table_name = 'WORKRECORD'", conn);
                if (Convert.ToInt32(await checkWr.ExecuteScalarAsync()) == 0)
                {
                    var sql = @"
                        CREATE TABLE WorkRecord (
                            workrcId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            empid VARCHAR2(255) NOT NULL,
                            date_col DATE NOT NULL,
                            workStart TIMESTAMP,
                            workEnd TIMESTAMP,
                            worktime NUMBER,
                            codeRowPerDay VARCHAR2(255),
                            docPagePerDay VARCHAR2(255),
                            consultation CLOB,
                            description CLOB,
                            createat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            createdBy VARCHAR2(255),
                            updatedBy VARCHAR2(255)
                        )
                    ";
                    // Note: 'date' is a reserved word in Oracle, causing issues if used as column name unquoted.
                    // However, we can quote it "date". 
                    // Let's use quotes.
                    sql = sql.Replace("date_col", "\"date\""); 
                    await new OracleCommand(sql, conn).ExecuteNonQueryAsync();

                    await new OracleCommand("CREATE INDEX idx_wr_date ON WorkRecord(\"date\")", conn).ExecuteNonQueryAsync();
                    await new OracleCommand("CREATE INDEX idx_wr_empid ON WorkRecord(empid)", conn).ExecuteNonQueryAsync();
                }

                Console.WriteLine("[Oracle] Attendance tables initialized");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error initializing attendance tables: {ex.Message}");
            }
        }

        public async Task ClearDataAsync()
        {
            if (!IsEnabled) return;
            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();
                await new OracleCommand("TRUNCATE TABLE WorkRecord", conn).ExecuteNonQueryAsync();
                await new OracleCommand("TRUNCATE TABLE attendance_logs", conn).ExecuteNonQueryAsync();
                Console.WriteLine("[Oracle] Data cleared");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error clearing data: {ex.Message}");
            }
        }

        public async Task<Employee?> GetEmployeeAsync(string empId)
        {
            if (!IsEnabled) return null;
            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();
                await using var cmd = new OracleCommand("SELECT empId, empnickName, empGivenName, empFamilyName FROM Employee WHERE empId = :empId", conn);
                cmd.Parameters.Add(":empId", empId);
                
                using var reader = await cmd.ExecuteReaderAsync();
                if (await reader.ReadAsync())
                {
                    return new Employee
                    {
                        EmpId = reader.GetString(0),
                        EmpNickName = reader.IsDBNull(1) ? "" : reader.GetString(1),
                        EmpGivenName = reader.IsDBNull(2) ? "" : reader.GetString(2),
                        EmpFamilyName = reader.IsDBNull(3) ? "" : reader.GetString(3)
                    };
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error getting employee: {ex.Message}");
            }
            return null;
        }

        public async Task<WorkRecord?> GetTodayWorkRecordAsync(string empId)
        {
            if (!IsEnabled) return null;
            try
            {
                var today = DateTime.Today;
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();
                await using var cmd = new OracleCommand(@"
                    SELECT workrcId, empid, ""date"", workStart, workEnd, worktime 
                    FROM WorkRecord 
                    WHERE empid = :empId AND ""date"" = :dateVal", conn); 
                cmd.Parameters.Add(":empId", empId);
                cmd.Parameters.Add(":dateVal", today);

                using var reader = await cmd.ExecuteReaderAsync();
                if (await reader.ReadAsync())
                {
                    TimeSpan? workStart = null;
                    if (!reader.IsDBNull(3)) workStart = reader.GetDateTime(3).TimeOfDay; // Simplified
                    
                    TimeSpan? workEnd = null;
                    if (!reader.IsDBNull(4)) workEnd = reader.GetDateTime(4).TimeOfDay;

                    return new WorkRecord
                    {
                        WorkRcId = reader.GetInt32(0),
                        EmpId = reader.GetString(1),
                        Date = reader.GetDateTime(2),
                        WorkStart = workStart,
                        WorkEnd = workEnd,
                        WorkTime = reader.IsDBNull(5) ? null : reader.GetDouble(5) 
                    };
                }
            }
            catch (Exception ex)
            {
                // Console.WriteLine($"[Oracle] Error getting WorkRecord: {ex.Message}");
            }
            return null;
        }

        public async Task CreateWorkRecordAsync(WorkRecord record)
        {
            if (!IsEnabled) return;
            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();
                var sql = @"
                    INSERT INTO WorkRecord (empid, ""date"", workStart, workEnd, worktime, createat)
                    VALUES (:empId, :dateVal, :workStart, :workEnd, :workTime, :createdAt)
                ";
                await using var cmd = new OracleCommand(sql, conn);
                
                // Construct DateTimes for TimeSpans because Oracle doesn't have TIME type, typically use TIMESTAMP
                DateTime? start = record.WorkStart.HasValue ? record.Date.Add(record.WorkStart.Value) : null;
                DateTime? end = record.WorkEnd.HasValue ? record.Date.Add(record.WorkEnd.Value) : null;

                cmd.Parameters.Add(":empId", record.EmpId);
                cmd.Parameters.Add(":dateVal", record.Date);
                cmd.Parameters.Add(":workStart", (object?)start ?? DBNull.Value);
                cmd.Parameters.Add(":workEnd", (object?)end ?? DBNull.Value);
                cmd.Parameters.Add(":workTime", (object?)record.WorkTime ?? DBNull.Value);
                cmd.Parameters.Add(":createdAt", (object?)record.CreatedAt ?? DateTime.Now);
                
                await cmd.ExecuteNonQueryAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error creating WorkRecord: {ex.Message}");
            }
        }

        public async Task UpdateWorkRecordAsync(WorkRecord record)
        {
            if (!IsEnabled) return;
            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();
                var sql = @"
                    UPDATE WorkRecord 
                    SET workEnd = :workEnd, worktime = :workTime, updatedAt = :updatedAt
                    WHERE workrcId = :id
                ";
                await using var cmd = new OracleCommand(sql, conn);
                
                DateTime? end = record.WorkEnd.HasValue ? record.Date.Add(record.WorkEnd.Value) : null;

                cmd.Parameters.Add(":workEnd", (object?)end ?? DBNull.Value);
                cmd.Parameters.Add(":workTime", (object?)record.WorkTime ?? DBNull.Value);
                cmd.Parameters.Add(":updatedAt", DateTime.Now);
                cmd.Parameters.Add(":id", record.WorkRcId);

                await cmd.ExecuteNonQueryAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error updating WorkRecord: {ex.Message}");
            }
        }

        public void Dispose()
        {
            // OracleConnection doesn't need explicit disposal at provider level
        }
    }
}
