using System;
using System.Threading.Tasks;
using Oracle.ManagedDataAccess.Client;

namespace ZKTecoRealTimeLog.Database
{
    /// <summary>
    /// Oracle database provider
    /// </summary>
    public class OracleProvider : IDatabaseProvider
    {
        #region Fields & Properties

        private readonly string _connectionString;
        private readonly bool _enabled;

        public string ProviderName => "Oracle";
        public bool IsEnabled => _enabled;

        #endregion

        #region Constructor

        public OracleProvider(DatabaseConfig config)
        {
            _enabled = config.Enabled;

            if (!string.IsNullOrEmpty(config.ConnectionString))
            {
                _connectionString = config.ConnectionString;
            }
            else
            {
                // Default port for Oracle is 1521
                var port = string.IsNullOrEmpty(config.Port) ? "1521" : config.Port;
                _connectionString = $"Data Source={config.Host}:{port}/{config.Database};User Id={config.User};Password={config.Password};";
            }
        }

        #endregion

        #region IDatabaseProvider Implementation

        public async Task<bool> TestConnectionAsync()
        {
            if (!IsEnabled) return false;

            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();
                return true;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Connection test failed: {ex.Message}");
                return false;
            }
        }

        public async Task InitializeDatabaseAsync()
        {
            if (!IsEnabled) return;

            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();

                // Check if table exists
                var checkTableSql = "SELECT COUNT(*) FROM user_tables WHERE table_name = 'ATTENDANCE_LOGS'";
                await using var checkCmd = new OracleCommand(checkTableSql, conn);
                var tableExists = Convert.ToInt32(await checkCmd.ExecuteScalarAsync()) > 0;

                if (!tableExists)
                {
                    var createTableSql = @"
                        CREATE TABLE attendance_logs (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id VARCHAR2(50) NOT NULL,
                            event_time TIMESTAMP NOT NULL,
                            is_valid NUMBER(1) NOT NULL,
                            att_state NUMBER NOT NULL,
                            att_state_desc VARCHAR2(50),
                            verify_method NUMBER NOT NULL,
                            verify_method_desc VARCHAR2(50),
                            work_code NUMBER DEFAULT 0,
                            device_ip VARCHAR2(50),
                            device_name VARCHAR2(100),
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                        )
                    ";
                    await using var createCmd = new OracleCommand(createTableSql, conn);
                    await createCmd.ExecuteNonQueryAsync();

                    var createIndex1 = "CREATE INDEX idx_att_logs_user_id ON attendance_logs(user_id)";
                    await using var idx1Cmd = new OracleCommand(createIndex1, conn);
                    await idx1Cmd.ExecuteNonQueryAsync();

                    var createIndex2 = "CREATE INDEX idx_att_logs_event_time ON attendance_logs(event_time)";
                    await using var idx2Cmd = new OracleCommand(createIndex2, conn);
                    await idx2Cmd.ExecuteNonQueryAsync();
                }

                Console.WriteLine("[Oracle] Database initialized successfully");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error initializing database: {ex.Message}");
            }
        }

        public async Task InsertAttendanceLogAsync(
            string enrollNumber, DateTime eventTime, bool isValid, int attState, string attStateDesc,
            int verifyMethod, string verifyMethodDesc, int workCode, string? deviceIp = null, string? deviceName = null)
        {
            if (!IsEnabled) return;

            try
            {
                await using var conn = new OracleConnection(_connectionString);
                await conn.OpenAsync();

                var insertSql = @"
                    INSERT INTO attendance_logs 
                    (user_id, event_time, is_valid, att_state, att_state_desc, verify_method, verify_method_desc, work_code, device_ip, device_name)
                    VALUES 
                    (:userId, :eventTime, :isValid, :attState, :attStateDesc, :verifyMethod, :verifyMethodDesc, :workCode, :deviceIp, :deviceName)
                ";

                await using var cmd = new OracleCommand(insertSql, conn);
                cmd.Parameters.Add(":userId", enrollNumber);
                cmd.Parameters.Add(":eventTime", eventTime);
                cmd.Parameters.Add(":isValid", isValid ? 1 : 0);
                cmd.Parameters.Add(":attState", attState);
                cmd.Parameters.Add(":attStateDesc", attStateDesc);
                cmd.Parameters.Add(":verifyMethod", verifyMethod);
                cmd.Parameters.Add(":verifyMethodDesc", verifyMethodDesc);
                cmd.Parameters.Add(":workCode", workCode);
                cmd.Parameters.Add(":deviceIp", (object?)deviceIp ?? DBNull.Value);
                cmd.Parameters.Add(":deviceName", (object?)deviceName ?? DBNull.Value);

                await cmd.ExecuteNonQueryAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"[Oracle] Error inserting attendance log: {ex.Message}");
            }
        }

        #endregion

        #region IDisposable

        public void Dispose()
        {
            // OracleConnection doesn't need explicit disposal at provider level
        }

        #endregion
    }
}

